export const ALZHEIMERS_FACTORS = {
  MEDICATIONS: {
    APPROVED: [
      'Acarbose',
      'Aducanumab',
      'Allopregnanolone',
      'Ambrisentan',
      'AMX0035',
      'Artesunate',
      'Atomoxetine',
      'Baricitinib',
      'Bempedoic acid',
      'Bumetanide',
      'Cannabidiol',
      'Cilostazol',
      'Colchicine',
      'Dabigatran',
      'Dexmedetomidine',
      'DFMO',
      'Dimethyl Fumarate',
      'Donepezil',
      'Duloxetine',
      'Edaravone',
      'Efavirenz',
      'EPA',
      'Estetrol',
      'Etifoxine',
      'Fasudil',
      'Fenofibrate',
      'Galantamine',
      'Guanfacine',
      'Hachimijiogan',
      'Hydroxychloroquine',
      'Ibrutinib',
      'Ibudilast',
      'Igmesine',
      'Ivermectin',
      'Lamivudine',
      'Leflunomide',
      'Lenalidomide',
      'Levetiracetam',
      'Memantine',
      'Metformin',
      'Methotrexate',
      'Methylene Blue',
      'Minocycline',
      'Mirabegron',
      'Mirodenafil',
      'Modafinil',
      'Montelukast',
      'Nabilone',
      'Naltrexone',
      'Nicotine',
      'Nilotinib',
      'Nitazoxanide',
      'Nooept',
      'Omaveloxolone',
      'Pemafibrate',
      'Pentoxifylline',
      'Pioglitazone',
      'Piracetam',
      'Ramelteon',
      'Rapamycin',
      'Rasagiline',
      'Retigabine',
      'Rhein',
      'Riluzole',
      'Rivastigmine',
      'Roflumilast',
      'Rolipram',
      'Rotigotine',
      'Selegiline',
      'Semaglutide',
      'Semax',
      'Sodium Oligomannate',
      'Sodium Phenylbutyrate',
      'Sulodexide',
      'Suvorexant',
      'Tacrolimus',
      'Ticagrelor',
      'Trametinib',
      'Trazodone',
      'Valacyclovir',
      'Vorinostat',
      'Vortioxetine',
      'YangXue QingNao',
      'Zileuton',
    ],
    IN_DEVELOPMENT: [
      'Lecanemab',
      'Donanemab',
      'Gantenerumab',
      '17α-Estradiol',
      '2-Deoxy-D-Glucose',
      '2-Hydroxybenzylamine',
      '3K3A-Activated Protein C',
      'A3R Agonists',
      'AAV-hTERT',
      'Aha1 Inhibitors',
      'ALDH2 activators',
      'ALZ-801',
      'Angiotensin 1-7',
      'ANGPTL3-Targeted Therapies',
      'Anti-Atherosclerotic Nanoparticles',
      'Anti-C1q',
      'Anti-CD22',
      'Anti-IL-11',
      'Apabetalone',
      'Apilimod',
      'AR1001',
      'AZ-67',
      'Azeliragon',
      'Bardaloxone Methyl',
      'BIIB080',
      'BMS-984923 (ALX-001)',
      'BPN14770',
      'Bryostatin',
      'Buntanetap',
      'Calmodulin-like skin protein',
      'Cambinol',
      'CaMKK2 Inhibitors',
      'Carnosic acid',
      'Caspase 2 Inhibitors',
      'CETP Inhibitors',
      'cGAS-STING',
      'CK2 Inhibitors',
      'CP2',
      'Crisdesalazine',
      'Cutamesine',
      'CSL112',
      'CT1812 (Elayta)',
      'Dapansutrile',
      'DHED',
      'Dihexa',
      'DYRK1A Inhibitors',
      'EC5026',
      'EGX358',
      'Elafibranor',
      'ENT1 inhibitors',
      'EP2 Antagonists',
      'Exosomes',
      'FGF21',
      'Fractalkine Modulators',
      'FSH blocking antibody',
      'Galectin-3 Inhibitors',
      'GDF-11',
      'Gingipain Inhibitors',
      'Ginsenoside Rg1',
      'Ginsenoside Rg3',
      'Gintonin',
      'GPR39 Agonists',
      'HBX',
      'HDAC3 Inhibitors',
      'Homotaurine',
      'Hsp90 inhibitors',
      'Humanin and humanin analogs',
      'Hydrogen sulfide',
      'Hydroxypropyl-β-cyclodextrin',
      'IBC-Ab002',
      'IGF1',
      'Immunoproteasome Inhibitors',
      'Intranasal Glutathione',
      'Intranasal Insulin',
      'Intravenous Mesenchymal Stem Cells',
      'Irisin',
      'ISRIB',
      'J147',
      'Klotho',
      'KPT-350',
      'L3MBTL1 Inhibitors',
      'Ligustilide',
      'LINE1 Inhibition',
      'LM11A-31 (C-31)',
      'Lp(a)',
      'Lonafarnib',
      'Lrp1 Modulators',
      'LRRK2 Inhibitors',
      'LXR Agonists',
      'MANF',
      'MARK4 Inhibitors',
      'MFGE8',
      'Mitochondrial Transplantation',
      'MMF Prodrugs',
      'MOTS-c',
      'MP101/MP201',
      'MSUT2 Inhibitors',
      'NE3107 (HE3286)',
      'Nicotinamide Mononucleotide',
      'NLRP3 Inhibitors',
      'NNI-362',
      'Notum Inhibitors',
      'NPTX2 Modulator',
      'Nrf2 Activators',
      'Nrf2 PPI Inhibitors',
      'NSC001',
      'NX210c',
      'O-GlcNAcase Inhibitors',
      'OGG1 Agonists',
      'Olamkicept',
      'ORM-12741',
      'Osteocalcin',
      'P021',
      'P110',
      'P2X7R Inhibitors',
      'P2Y1R Inhibitors',
      'P2Y6R Agonist',
      'P38α MAPK Inhibitors',
      'PAR4 Antagonists',
      'Pepinemab',
      'Piromelatine',
      'Plasma exchange',
      'Pomaglumetad',
      'PPARδ Agonists',
      'Pridopidine',
      'Prosaposin',
      'PRX-03140',
      'Psilocybin',
      'Rabeximod',
      'REST/NRSF Modulators',
      'RIPK1 Inhibitors',
      'Roluperidone',
      'RT001',
      'RTA-405',
      'S1P4R Antagonists',
      'S3QELs',
      'S6K1 Inhibitors',
      'SAGE-718',
      'SBT-272',
      'Senolytics',
      'SFX01',
      'SHIP1 Modulators',
      'Simufilam (PTI-125)',
      'SKQ1',
      'Small humanin-like peptides',
      'SPG-302',
      'SS-31',
      'Sterubin',
      'SXC-2023',
      'Syk Inhibitors',
      'T regulatory cell Therapies',
      'T3D-959',
      'Tanespimycin',
      'THIK-1 Inhibitors',
      'THN391',
      'Thyromimetics',
      'TLR2 Inhibitors',
      'TLR4 Inhibitors',
      'Tramiprosate',
      'Traneurocin (NA-831)',
      'TRH',
      'Trichostatin-A',
      'Trodusquemine',
      'Troriluzole',
      'TRPM2 Inhibitors',
      'TRPML1 Agonists',
      'TQS-168',
      'URMC-099',
      'Urolithin A',
      'Vafidemstat (ORY-2001)',
      'Verdiperstat',
      'Volanesorsen',
      'VX-765',
      'Xanamem',
      'XPro1595'
    ]
  },

  NON_PHARMACOLOGIC: [
    'Cognitive stimulation therapy',
    'Physical exercise',
    'Social engagement',
    'Music therapy',
    'Art therapy',
    'Reminiscence therapy',
    'Sleep hygiene',
    'Stress reduction',
    'Breathing Techniques',
    'Cold-water immersion',
    'CPAP for Obstructive Sleep Apnea',
    'Focused Ultrasound',
    'Inspiratory Muscle Strength Training',
    'Meditation',
    'Molecular Hydrogen',
    'Oxygen Nanobubbles',
    'Sauna',
    'Time-Restricted Eating',
    'Transcranial Direct Current Stimulation',
    'Transcranial Magnetic Stimulation',
    'Vagal Nerve Stimulation',
    'Whole Body Cryotherapy'
  ],

  DIETARY_FACTORS: {
    BENEFICIAL: [
      'Mediterranean diet',
      'MIND diet',
      'Omega-3 fatty acids',
      'Green leafy vegetables',
      'Berries',
      'Nuts',
    ],
    HARMFUL: [
      'Processed foods',
      'High sugar intake',
      'Excessive alcohol',
    ]
  },

  SUPPLEMENTS: [
    'Vitamin B12',
    'Vitamin D',
    'Vitamin E',
    'DHA (Docosahexaenoic acid)',
    'Curcumin',
    'Ginkgo biloba',
    '7,8 Dihydroxyflavone',
    'Aged Garlic Extract',
    'Agmatine',
    'Alpha-GPC',
    'Alpha-ketoglutarate',
    'Apigenin',
    'Apoaequorin',
    'Astaxanthin',
    'Astragalus',
    'Bacopa Monnieri',
    'Benfotiamine',
    'Berberine',
    'Boswellia',
    'Centella Asiatica',
    'Centrophenoxine',
    'Citicoline',
    'Coffee Fruit',
    'Creatine',
    'Dihydromyricetin',
    'Dinh Lang',
    'D-serine',
    'EGCG',
    'Epithalamin & Epithalon',
    'Ergothioneine',
    'Fisetin',
    'Fucoidan',
    'Genistein',
    'Glucosamine',
    'Honokiol',
    'Huperzine-A',
    'Kamikihito',
    'Krill Oil',
    'Licorice Flavonoids',
    "Lion's Mane Mushroom",
    'L-Serine',
    'L-Theanine',
    'Lysophosphatidylcholine-Omega3',
    'Magnesium',
    'Medium Chain Triglycerides',
    'Melatonin',
    'MitoQ',
    'N-Acetylcysteine',
    'NDGA',
    'Nicotinamide Riboside',
    'Omega-3 Fatty Acids',
    'Oxaloacetate',
    'Palmitoylethanolamide',
    'Panax Ginseng',
    'Pantethine',
    'PB125',
    'Phosphatidylcholine & Lecithin',
    'Phosphatidylserine',
    'Plasmalogen',
    'Policosanol',
    'Polyamine',
    'Postbiotics',
    'Probiotics',
    'Protandim',
    'Pterostilbene',
    'PTI-00703',
    'Resveratrol',
    'S-Adenosylmethionine',
    'S-equol',
    'Sage',
    'Selenium',
    'Shankhpushpi',
    'Silymarin',
    'Soy Isoflavones',
    'Sulforaphane',
    'Souvenaid',
    'Taurine',
    'Tauroursodeoxycholic Acid',
    'TA-65',
    'Tinospora Cordifolia',
    'Trehalose',
    'Triphala',
    'Turkey Tail Mushrooms',
    'Ursolic Acid',
    'Vinpocetine',
    'Vitamin B6, B12, and Folate',
    'Vitamin K2'
  ],

  RISK_FACTORS: {
    MODIFIABLE: [
      'Physical inactivity',
      'Smoking',
      'Poor diet',
      'Limited cognitive stimulation',
      'Social isolation',
      'Diabetes',
      'Hypertension',
      'Obesity',
      'Depression',
      'Air Pollution',
      'Aluminum exposure',
      'Benzodiazepine use',
      'Diphenhydramine use',
      'Erythritol and Xylitol consumption',
      'Mold and Mycotoxin exposure',
      'Oxymetazoline use',
      'Plastic exposure',
      'Sleep deficit or excess',
      'Textile Toxin exposure',
    ],
    NON_MODIFIABLE: [
      'Age',
      'Family history',
      'APOE ε4 gene',
      'Down syndrome',
      'Polygenic Risk Score',
      'Epigenetic Clock status',
    ]
  }
}

export type AlzheimersFactorsType = typeof ALZHEIMERS_FACTORS; 