version: '3.8'
services:
  db:
    image: ankane/pgvector:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: wishonia_test
    ports:
      - "5432:5432"
    container_name: wishonia-postgres
    volumes:
      - .postgres:/var/lib/postgresql/data