packages:
  - '.'

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - bufferutil
  - canvas
  - es5-ext
  - esbuild
  - prisma
  - sharp
  - utf-8-validate
  - yarn
