/**
 * Decentralized FDA API
 * A platform for quantifying the effects of every drug, supplement, food, and other factor on your health.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConversionStep } from "../models/ConversionStep"
import { VariableCombinationOperationEnum, VariableFillingTypeEnum } from "./GlobalVariable"

export class Unit {
  /**
   * Unit abbreviation
   */
  "abbreviatedName": string
  /**
   * Ex: 1
   */
  "advanced"?: number
  /**
   * Unit category name
   */
  "categoryName": string
  /**
   * Unit category ID
   */
  "unitCategoryId": number
  /**
   * How measurements should be combined
   */
  combinationOperation?: VariableCombinationOperationEnum | null
  /**
   * Conversion steps list
   */
  "conversionSteps": Array<ConversionStep>
  /**
   * How missing values should be handled
   */
  "fillingType": VariableFillingTypeEnum
  /**
   * Value to use when filling missing data
   */
  "fillingValue": number | null
  /**
   * Hint text for input
   */
  "hint"?: string | null
  /**
   * Unit ID
   */
  "id": number
  /**
   * Icon image URL
   */
  "image"?: string
  /**
   * Whether unit can be tracked manually
   */
  "manualTracking": number
  /**
   * Maximum allowed value
   */
  "maximumValue": number | null
  /**
   * Minimum allowed value
   */
  "minimumValue": number | null
  /**
   * Unit name
   */
  "name": string
  /**
   * Measurement scale type
   */
  "scale"?: "ratio" | "interval" | "ordinal"
  /**
   * Unit suffix
   */
  "suffix"?: string | null
  /**
   * Alternative names for the unit
   */
  "synonyms"?: string[]
  /**
   * Font Awesome icon name
   */
  "fontAwesome"?: string | null
  /**
   * Input type for form fields
   */
  "inputType"?: string | null
  /**
   * Maximum daily value allowed
   */
  "maximumDailyValue"?: number | null
  /**
   * Default value
   */
  "defaultValue"?: number | null

  "add"?: number | null
  "multiply"?: number | null

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: "abbreviatedName",
      baseName: "abbreviatedName",
      type: "string",
      format: "",
    },
    {
      name: "advanced",
      baseName: "advanced",
      type: "number",
      format: "",
    },
    {
      name: "categoryName",
      baseName: "categoryName",
      type: "string",
      format: "",
    },
    {
      name: "unitCategoryId",
      baseName: "unitCategoryId",
      type: "number",
      format: "",
    },
    {
      name: "conversionSteps",
      baseName: "conversionSteps",
      type: "Array<ConversionStep>",
      format: "",
    },
    {
      name: "fillingType",
      baseName: "fillingType",
      type: "VariableFillingTypeEnum",
      format: "",
    },
    {
      name: "fillingValue",
      baseName: "fillingValue",
      type: "number",
      format: "",
    },
    {
      name: "hint",
      baseName: "hint",
      type: "string",
      format: "",
    },
    {
      name: "id",
      baseName: "id",
      type: "number",
      format: "",
    },
    {
      name: "image",
      baseName: "image",
      type: "string",
      format: "",
    },
    {
      name: "manualTracking",
      baseName: "manualTracking",
      type: "number",
      format: "",
    },
    {
      name: "maximumValue",
      baseName: "maximumValue",
      type: "number",
      format: "",
    },
    {
      name: "minimumValue",
      baseName: "minimumValue",
      type: "number",
      format: "",
    },
    {
      name: "name",
      baseName: "name",
      type: "string",
      format: "",
    },
    {
      name: "scale",
      baseName: "scale",
      type: "string",
      format: "",
    },
    {
      name: "suffix",
      baseName: "suffix",
      type: "string",
      format: "",
    },
    {
      name: "synonyms",
      baseName: "synonyms",
      type: "Array<string>",
      format: "",
    },
    {
      name: "fontAwesome",
      baseName: "fontAwesome",
      type: "string",
      format: "",
    },
    {
      name: "inputType",
      baseName: "inputType",
      type: "string",
      format: "",
    },
    {
      name: "maximumDailyValue",
      baseName: "maximumDailyValue",
      type: "number",
      format: "",
    },
    {
      name: "defaultValue",
      baseName: "defaultValue",
      type: "number",
      format: "",
    },
  ]

  static getAttributeTypeMap() {
    return Unit.attributeTypeMap
  }

  public constructor() {}
}

export type UnitCategoryEnum =
  | "Distance"
  | "Duration"
  | "Energy"
  | "Frequency"
  | "Miscellany"
  | "Pressure"
  | "Proportion"
  | "Rating"
  | "Temperature"
  | "Volume"
  | "Weight"
  | "Count"
