import {
  ChevronLeft,
  Github,
  CircleDot,
  Bug,
  X,
  Copy,
  MoreHorizontal,
  Plus,
  AlertTriangle,
  Calendar,
  History,
  Activity,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Flame,
  Moon,
  Sun,
  FileText,
  Bell,
  Bomb,
  BookOpen,
  Camera,
  BarChart,
  PieChart,
  Stethoscope,
  Edit,
  Eye,
  EyeOff,
  Home,
  Inbox,
  Lightbulb,
  Heart,
  HelpCircle,
  Star,
  Bot,
  Scroll,
  Lock,
  Search,
  Pill,
  User,
  Trash2,
  Loader,
  LogOut,
  Settings,
  Pencil,
  LayoutDashboard,
  SlidersHorizontal,
  Building,
  Scale,
  FileEdit,
  MessageSquare,
  Vote,
  Frown,
  Hand,
  Shield,
  FileQuestion,
  GraduationCap,
  Scroll as ScrollIcon,
  PiggyBank
} from "lucide-react"

export type IconKeys = keyof typeof icons

type IconsType = {
  [key in IconKeys]: React.ElementType
}

const icons = {
  // Providers
  google: CircleDot,
  github: Github,
  bug: Bug,

  // Dashboard Icons
  dashboard: LayoutDashboard,
  activity: Activity,
  measurement: Pencil,
  settings: Settings,
  camera: Camera,
  write: MessageSquare,
  wishingWell: Activity,
  bomb: Bomb,
  skull: AlertTriangle,
  vote: Vote,
  health: BookOpen,
  peace: Heart,
  results: BarChart,
  disease: Stethoscope,
  home: Home,
  frown: Frown,
  pieChart: PieChart,
  docs: FileText,
  robot: Bot,
  scroll: ScrollIcon,
  safe: Lock,
  conditions: Stethoscope,
  treatments: Pill,
  search: Search,
  trials: BarChart,
  measurements: Pencil,
  userVariables: User,
  predictorSearch: Search,
  inbox: Inbox,

  clipboard: Copy,

  // Mode Toggle
  moon: Moon,
  sun: Sun,

  // Navigation
  back: ChevronLeft,
  next: ChevronRight,
  up: ChevronUp,
  down: ChevronDown,
  close: X,

  // Common
  trash: Trash2,
  spinner: Loader,
  userAlt: User,
  ellipsis: MoreHorizontal,
  warning: AlertTriangle,
  add: Plus,
  reminder: Bell,
  history: History,
  charts: BarChart,
  signout: LogOut,
  calendar: Calendar,
  sort: SlidersHorizontal,
  fire: Flame,
  statsBar: BarChart,
  mixer: SlidersHorizontal,
  check: Check,
  star: Star,
  ranking: Star,
  question: HelpCircle,
  volunteer: Hand,
  lightbulb: Lightbulb,
  edit: Edit,
  eye: Eye,
  eyeOff: EyeOff,
  book: BookOpen,
  pencil: Pencil,
  chevronLeft: ChevronLeft,
  shield: Shield,
  wiki: FileQuestion,
  studies: GraduationCap,
  petition: Scroll,
  savings: PiggyBank,

  // Add these new icons
  document: FileText,
  building: Building,
  pencilSquare: FileEdit,
  scale: Scale,
}

export const Icons: IconsType = icons